<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('BlogTemplate', 'doctrine');

/**
 * BaseBlogTemplate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $category_id
 * @property string $content
 * 
 * @method integer      getId()          Returns the current record's "id" value
 * @method integer      getCategoryId()  Returns the current record's "category_id" value
 * @method string       getContent()     Returns the current record's "content" value
 * @method BlogTemplate setId()          Sets the current record's "id" value
 * @method BlogTemplate setCategoryId()  Sets the current record's "category_id" value
 * @method BlogTemplate setContent()     Sets the current record's "content" value
 * 
 * @package    tbshare
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBlogTemplate extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('blog_template');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('category_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('content', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}