<?php

/**
 * BlogTemplateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BlogTemplateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BlogTemplateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BlogTemplate');
    }
}