<?php

/**
 * BlogAccountTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BlogAccountTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BlogAccountTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BlogAccount');
    }
    
    public function addOrUpdateBlogAccount($user_id, $platform_id, $token="",$name="",$expires_in=0,$var1="",$var2="",$var3="",$var4="",$var5="",$var6=""){
      $blogAccount = Doctrine::getTable("BlogAccount")->findOneBy("customer_idAndplatform_id", array($user_id,$platform_id));
      if(!$blogAccount)
          $blogAccount = new BlogAccount();
      $blogAccount->setCustomerId($user_id);
      $blogAccount->setPlatformId($platform_id);
      $blogAccount->setToken($token);
      $blogAccount->setName($name);
      $blogAccount->setExpiresIn($expires_in);
      $blogAccount->setVar1($var1);
      $blogAccount->setVar2($var2);
      $blogAccount->setVar3($var3);
      $blogAccount->setVar4($var4);
      $blogAccount->setVar5($var5);
      $blogAccount->setVar6($var6);
      
      $blogAccount->save();
  }
           
}