<?php

/**
 * Customer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    tbshare
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Customer extends BaseCustomer
{
    public function countLastPublishTimes(){
      
      $last_publish_time = $this->getLastQuickPublishTime();
      if($last_publish_time==""){
          $last_publish_times = sfConfig::get("app_public_publish_times");
      }else{
          if(strtotime(date("Y-m-d",strtotime($last_publish_time))) == strtotime(date("Y-m-d"))){
              $last_publish_times = $this->get("quick_publish_times");
          }else if(strtotime(date("Y-m-d",strtotime($last_publish_time))) < strtotime(date("Y-m-d"))){
              $this->set("quick_publish_times", sfConfig::get("app_public_publish_times"));
              $this->save();
              $last_publish_times = sfConfig::get("app_public_publish_times");
          }
      }
      return $last_publish_times;
    }
    public function updatePublicPublishTimes(){
      $last_publish_time = $this->getLastQuickPublishTime();
      if($last_publish_time==""){
          $last_publish_times = sfConfig::get("app_public_publish_times");
          $this->set("quick_publish_times", $last_publish_times-1);
          $this->set("last_quick_publish_time", date("Y-m-d H:m:s"));
          $this->save();
      }else{
          if(strtotime(date("Y-m-d",strtotime($last_publish_time))) == strtotime(date("Y-m-d"))){
              $last_publish_times = $this->get("quick_publish_times");
              $this->set("last_quick_publish_time", date("Y-m-d H:m:s"));
              $this->set("quick_publish_times", $last_publish_times-1);
              $this->save();
          }else if(strtotime(date("Y-m-d",strtotime($last_publish_time))) < strtotime(date("Y-m-d"))){
              $this->set("quick_publish_times", sfConfig::get("app_public_publish_times")-1);
              $this->set("last_quick_publish_time", date("Y-m-d H:m:s"));
              $this->save();

          }
      }
    }
}