<?php

/**
 * TemplateCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TemplateCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TemplateCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TemplateCategory');
    }
}