Blog:
  connection: doctrine
  tableName: blog
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    customer_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    platform_id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: false
      notnull: true
      autoincrement: false
    product_id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    contents:
      type: string(512)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    weibo_id:
      type: string(128)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    publish_at:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: true
      autoincrement: false
    is_public:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: true
      autoincrement: false
  relations:
    Customer:
      local: customer_id
      foreign: id
      type: one
    Platform:
      local: platform_id
      foreign: id
      type: one
BlogAccount:
  connection: doctrine
  tableName: blog_account
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    platform_id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: false
      notnull: true
      autoincrement: false
    customer_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    name:
      type: string(64)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    token:
      type: string(256)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    expires_in:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: true
      autoincrement: false
    var1:
      type: string(256)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    var2:
      type: string(256)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    var3:
      type: string(256)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    var4:
      type: string(256)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    var5:
      type: string(256)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    var6:
      type: string(256)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    is_enable:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      default: '1'
      notnull: true
      autoincrement: false
  relations:
    Platform:
      local: platform_id
      foreign: id
      type: one
    Customer:
      local: customer_id
      foreign: id
      type: one
BlogTemplate:
  connection: doctrine
  tableName: blog_template
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    category_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    content:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
Customer:
  connection: doctrine
  tableName: customer
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    nick:
      type: string(64)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    deadline:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    session_key:
      type: string(512)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    parameters:
      type: string(1024)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    sign:
      type: string(512)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    last_publish_time:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    last_quick_publish_time:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    quick_publish_times:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      default: '20'
      notnull: true
      autoincrement: false
  relations:
    Blog:
      local: id
      foreign: customer_id
      type: many
    BlogAccount:
      local: id
      foreign: customer_id
      type: many
    PublicAccount:
      local: id
      foreign: customer_id
      type: many
Platform:
  connection: doctrine
  tableName: platform
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: true
    name:
      type: string(128)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    description:
      type: string(512)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    register_url:
      type: string(256)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    image:
      type: string(128)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    auth_action:
      type: string(128)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    is_enable:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: true
      autoincrement: false
  relations:
    Blog:
      local: id
      foreign: platform_id
      type: many
    BlogAccount:
      local: id
      foreign: platform_id
      type: many
    PublicAccount:
      local: id
      foreign: platform_id
      type: many
PublicAccount:
  connection: doctrine
  tableName: public_account
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    platform_id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: false
      notnull: true
      autoincrement: false
    customer_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    name:
      type: string(64)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    token:
      type: string(256)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    expires_in:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: true
      autoincrement: false
    var1:
      type: string(256)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    var2:
      type: string(256)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    var3:
      type: string(256)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    var4:
      type: string(256)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    var5:
      type: string(256)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    var6:
      type: string(256)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    is_enable:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      default: '1'
      notnull: true
      autoincrement: false
  relations:
    Platform:
      local: platform_id
      foreign: id
      type: one
    Customer:
      local: customer_id
      foreign: id
      type: one
TemplateCategory:
  connection: doctrine
  tableName: template_category
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    name:
      type: string(128)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    description:
      type: string(512)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
